global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: incident-metrics-exporter
    metrics_path: /metrics
    static_configs:
      - targets:
          - metrics-exporter:8000
